---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
  labels:
    app: proxysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxysql
        tier: frontend
    spec:
      restartPolicy: Always
      containers:
      - image: plopix/docker-mysqlproxyprofiler
        name: proxysql
        ports:
        - containerPort: 3306
          name: proxysql-mysql
        env:
        - name: "BACKEND"
          value: "host:port"
